### ISSUE TITLE
As Tourismusverein Partschins I would like that e-mobility map web-components shows not only the link to suedtirolmobil, but also the link to the POI's web-site

### ISSUE THREAD

**Issue by rcavaliere** [noi-techpark/webcomp-mobility-echarging-map#66] opened 2023-01-31 06:22 UTC
- [x] Web component adjustments (POI link)
- [x] Tourist data quality check (POI web site) -> we should say in my opinion to update the source system (TIC Web of LTS?)

Additional request:

> wenn möglich bitte die Hotels und Restaurants mit unserer Website verlinken, d.h. bitte die jeweils unten angeführten Links bei der E-Ladestation in Rabland beim jeweiligen Betrieb hinzufügen: 

> Restaurant Hanswirt:[ https://www.merano-suedtirol.it/de/partschins-rabland-und-toell/natur-kultur/wasserwelten/trinkwasserauffuellpunkte-brunnen/rid-029415631134860A4F7FE1801A01C3B7-g-restaurant-hanswirt.html](https://www.merano-suedtirol.it/de/partschins-rabland-und-toell/natur-kultur/wasserwelten/trinkwasserauffuellpunkte-brunnen/rid-029415631134860A4F7FE1801A01C3B7-g-restaurant-hanswirt.html)

> Restaurant Ennemoser:[ https://www.merano-suedtirol.it/de/partschins-rabland-und-toell/essen-trinken/partschinser-kueche/gastronomiebetriebe/rid-0A14E5A098488EDEB49643107B826512-g-ennemoser.html](https://www.merano-suedtirol.it/de/partschins-rabland-und-toell/essen-trinken/partschinser-kueche/gastronomiebetriebe/rid-0A14E5A098488EDEB49643107B826512-g-ennemoser.html)

> Restaurant Rössl:[ https://www.merano-suedtirol.it/de/partschins-rabland-und-toell/essen-trinken/partschinser-kueche/gastronomiebetriebe/rid-751144E32CB35A66B1DDAFBCED402D25-g-restaurant-cafe-roessl.html](https://www.merano-suedtirol.it/de/partschins-rabland-und-toell/essen-trinken/partschinser-kueche/gastronomiebetriebe/rid-751144E32CB35A66B1DDAFBCED402D25-g-restaurant-cafe-roessl.html)

> Hotel Hanswirt:[ https://www.merano-suedtirol.it/de/partschins-rabland-und-toell/hotel-unterkunft/unterkunft-suchen-buchen/unterkuenfte-in-partschins-rabland-und-toell/rid-5DF21204ACF711D1BAAA00805A13E75D-hotel-hanswirt.html](https://www.merano-suedtirol.it/de/partschins-rabland-und-toell/hotel-unterkunft/unterkunft-suchen-buchen/unterkuenfte-in-partschins-rabland-und-toell/rid-5DF21204ACF711D1BAAA00805A13E75D-hotel-hanswirt.html)

> Pension Ennemoser:[ https://www.merano-suedtirol.it/de/partschins-rabland-und-toell/hotel-unterkunft/unterkunft-suchen-buchen/unterkuenfte-in-partschins-rabland-und-toell/rid-DB1CC909AEB711D1BAAA00805A13E75D-pension-ennemoser.html](https://www.merano-suedtirol.it/de/partschins-rabland-und-toell/hotel-unterkunft/unterkunft-suchen-buchen/unterkuenfte-in-partschins-rabland-und-toell/rid-DB1CC909AEB711D1BAAA00805A13E75D-pension-ennemoser.html)

> Garni Hotel Am Meilenstein:[ https://www.merano-suedtirol.it/de/partschins-rabland-und-toell/hotel-unterkunft/unterkunft-suchen-buchen/unterkuenfte-in-partschins-rabland-und-toell/rid-DB1CC916AEB711D1BAAA00805A13E75D-garni-hotel-am-meilenstein.html](https://www.merano-suedtirol.it/de/partschins-rabland-und-toell/hotel-unterkunft/unterkunft-suchen-buchen/unterkuenfte-in-partschins-rabland-und-toell/rid-DB1CC916AEB711D1BAAA00805A13E75D-garni-hotel-am-meilenstein.html)

> Zudem bitten wir Euch Rabland als Titel zu nehmen statt Rabla.

@RudiThoeni @dulvui @clezag could you please check this request and give me a feedback?

**Comment by clezag** [comment] 2023-02-08 15:54
@rcavaliere I've added the POI's website below the "More informations" link.
We've also fixed the "More informations" link to work as intended, as it was always linking to the suedtirol.info landing page instead of the actual URL

**Comment by RudiThoeni** [comment] 2023-02-08 16:39
@rcavaliere the other links that the TV requested if they find a possibility to insert it in TIC web and LTS delivers it to us as opendata we can add also this links otherwise we cannot

**Comment by rcavaliere** [comment] 2023-02-08 22:13
@clezag thanks! Where can I see the changes that you did?
@RudiThoeni fully agree on this, I will give this kind of feedback to them!

**Comment by RudiThoeni** [comment] 2023-02-08 22:59
> @clezag thanks! Where can I see the changes that you did?

On the webcomponent on testingmachine ;)

**Comment by rcavaliere** [comment] 2023-02-09 21:13
@clezag @RudiThoeni wonderful, I have checked the improvement, I think it's OK. Let's release this on production!

**Comment by clezag** [comment] 2023-02-13 08:30
@rcavaliere released in production

**Closed** 2023-02-13 14:45 UTC
